In [1]:
import sys
sys.path.append("../new_way/")

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

from api import vqvae_inference

In [6]:
model_route= r"/export/usuarios01/icmora/deploymentVQVAE-GitHub/deployment-VQVAE/data/vqvae_a1_m_best.pt"
data_path=r"/export/usuarios01/icmora/deploymentVQVAE/deployment-VQVAE/ignore/test_more_data.csv"
results_folder_path = r"/export/usuarios01/icmora/deploymentVQVAE-GitHub/deployment-VQVAE/api_test/results_inference"

In [ ]:
inference = vqvae_inference(model_route= model_route, device =  "cuda")

Model successfully loaded

In [8]:
print(inference.model)
print(inference.device)

VQVAE(
  (encoder): Encoder(
    (relu): ReLU()
    (dropout): Dropout1d(p=0.5, inplace=False)
    (intra_mask_1): Conv1d(10, 10, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn_intra_mask_1): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (intra_mask_2): Conv1d(10, 10, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn_intra_mask_2): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (pre_mask): Sequential(
      (0): Conv1d(10, 10, kernel_size=(3,), stride=(1,), padding=(1,))
      (1): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Conv1d(10, 10, kernel_size=(3,), stride=(1,), padding=(1,))
      (4): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU()
    )
    (conv1): Conv1d(20, 10, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn1): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv2): Conv1d(10, 20, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn2): BatchNorm1d(20, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv3): Conv1d(20, 40, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn3): BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv4): Conv1d(40, 40, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn4): BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv5): Conv1d(40, 60, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn5): BatchNorm1d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv6): Conv1d(60, 80, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn6): BatchNorm1d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv_layers): Sequential(
      (0): Conv1d(20, 10, kernel_size=(3,), stride=(1,), padding=(1,))
      (1): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Conv1d(10, 20, kernel_size=(3,), stride=(1,), padding=(1,))
      (4): BatchNorm1d(20, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU()
      (6): Conv1d(20, 40, kernel_size=(3,), stride=(1,), padding=(1,))
      (7): BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (8): ReLU()
      (9): Conv1d(40, 40, kernel_size=(3,), stride=(1,), padding=(1,))
      (10): BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (11): ReLU()
      (12): Conv1d(40, 60, kernel_size=(3,), stride=(1,), padding=(1,))
      (13): BatchNorm1d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (14): ReLU()
      (15): Conv1d(60, 80, kernel_size=(3,), stride=(1,), padding=(1,))
      (16): BatchNorm1d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (17): ReLU()
    )
  )
  (decoder): Decoder(
    (relu): ReLU()
    (id): Identity()
    (dropout): Dropout1d(p=0.5, inplace=False)
    (deconv1): ConvTranspose1d(80, 60, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn1): BatchNorm1d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (deconv2): ConvTranspose1d(60, 40, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn2): BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (deconv3): ConvTranspose1d(40, 40, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn3): BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (deconv4): ConvTranspose1d(40, 20, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn4): BatchNorm1d(20, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (deconv5): ConvTranspose1d(20, 10, kernel_size=(3,), stride=(1,), padding=(1,))
    (bn5): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (deconv_layers): Sequential(
      (0): ConvTranspose1d(80, 60, kernel_size=(3,), stride=(1,), padding=(1,))
      (1): BatchNorm1d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): ConvTranspose1d(60, 40, kernel_size=(3,), stride=(1,), padding=(1,))
      (4): BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU()
      (6): ConvTranspose1d(40, 40, kernel_size=(3,), stride=(1,), padding=(1,))
      (7): BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (8): ReLU()
      (9): ConvTranspose1d(40, 20, kernel_size=(3,), stride=(1,), padding=(1,))
      (10): BatchNorm1d(20, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (11): ReLU()
      (12): ConvTranspose1d(20, 10, kernel_size=(3,), stride=(1,), padding=(1,))
      (13): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (14): Identity()
    )
  )
  (quantizer): Quantizer()
)
cpu

In [9]:
%%time

inference.forward(data_path = data_path,
                  results_folder_path = results_folder_path,
)

Data successfully loaded
User index with duplicates: 301059
Duplicated dates:
        user  date_time      service  sleep_start  location_distance  \
894  301059 2024-12-30  DC_alicante          NaN                NaN
893  301059 2024-12-30  DC_alicante          NaN                NaN
840  301059 2024-12-31  DC_alicante          NaN                NaN
839  301059 2024-12-31  DC_alicante          NaN                NaN

     location_time_home  sleep_duration  activity_walking  app_usage_total  \
894                 NaN             NaN            6593.0              NaN
893                 NaN             NaN               NaN              NaN
840                 NaN             NaN               NaN              NaN
839                 NaN             NaN               NaN              NaN

     location_clusters_count  steps_steps_total  weekend  practiced_sport
894                      NaN             7939.0        0                1
893                      NaN                NaN        0                0
840                      NaN                NaN        0                0
839                      NaN                NaN        0                0
User index with duplicates: 301092
Duplicated dates:
        user  date_time      service  sleep_start  location_distance  \
910  301092 2024-12-30  DC_alicante          NaN                NaN
909  301092 2024-12-30  DC_alicante     -11824.0                NaN
856  301092 2024-12-31  DC_alicante          NaN                NaN
855  301092 2024-12-31  DC_alicante          NaN                NaN

     location_time_home  sleep_duration  activity_walking  app_usage_total  \
910                 NaN             NaN               NaN              NaN
909                 NaN         40200.0               NaN              NaN
856                 NaN             NaN               NaN              NaN
855                 NaN             NaN               NaN              NaN

     location_clusters_count  steps_steps_total  weekend  practiced_sport
910                      NaN             8191.0        0                0
909                      NaN                NaN        0                0
856                      NaN                NaN        0                0
855                      NaN                NaN        0                0

Out of 50, 48 were kept, and 2 were discarded due to duplicated dates.

[841063, 821046, 121094, 521052, 521075, 301056, 301057, 301058, 301101, 301060, 301061, 301063, 301064, 301066, 301068, 301069, 301075, 301079, 301077, 301076, 301067, 301074, 301072, 301091, 301097, 301093, 301088, 301086, 301083, 301082, 301081, 301080, 301084, 301071, 301070, 301098, 2011153, 301087, 301102, 301103, 301104, 301106, 301107, 301095, 301096, 2011151, 301100, 301085]
Patient ID: 841063, sample shape: (52, 13)
Patient ID: 821046, sample shape: (46, 13)
Patient ID: 121094, sample shape: (46, 13)
Patient ID: 521052, sample shape: (29, 13)
Patient ID: 521075, sample shape: (1, 13)
Patient ID: 301056, sample shape: (137, 13)
Patient ID: 301057, sample shape: (46, 13)
Patient ID: 301058, sample shape: (224, 13)
Patient ID: 301101, sample shape: (495, 13)
Patient ID: 301060, sample shape: (24, 13)
Patient ID: 301061, sample shape: (99, 13)
Patient ID: 301063, sample shape: (219, 13)
Patient ID: 301064, sample shape: (204, 13)
Patient ID: 301066, sample shape: (156, 13)
Patient ID: 301068, sample shape: (219, 13)
Patient ID: 301069, sample shape: (220, 13)
Patient ID: 301075, sample shape: (437, 13)
Patient ID: 301079, sample shape: (123, 13)
Patient ID: 301077, sample shape: (213, 13)
Patient ID: 301076, sample shape: (113, 13)
Patient ID: 301067, sample shape: (146, 13)
Patient ID: 301074, sample shape: (191, 13)
Patient ID: 301072, sample shape: (118, 13)
Patient ID: 301091, sample shape: (151, 13)
Patient ID: 301097, sample shape: (6, 13)
Patient ID: 301093, sample shape: (159, 13)
Patient ID: 301088, sample shape: (206, 13)
Patient ID: 301086, sample shape: (147, 13)
Patient ID: 301083, sample shape: (206, 13)
Patient ID: 301082, sample shape: (41, 13)
Patient ID: 301081, sample shape: (476, 13)
Patient ID: 301080, sample shape: (85, 13)
Patient ID: 301084, sample shape: (184, 13)
Patient ID: 301071, sample shape: (205, 13)
Patient ID: 301070, sample shape: (203, 13)
Patient ID: 301098, sample shape: (144, 13)
Patient ID: 2011153, sample shape: (50, 13)
Patient ID: 301087, sample shape: (217, 13)
Patient ID: 301102, sample shape: (200, 13)
Patient ID: 301103, sample shape: (100, 13)
Patient ID: 301104, sample shape: (124, 13)
Patient ID: 301106, sample shape: (83, 13)
Patient ID: 301107, sample shape: (24, 13)
Patient ID: 301095, sample shape: (198, 13)
Patient ID: 301096, sample shape: (26, 13)
Patient ID: 2011151, sample shape: (73, 13)
Patient ID: 301100, sample shape: (358, 13)
Patient ID: 301085, sample shape: (195, 13)
Forwarded Batch
Dataset saved to: /export/usuarios01/icmora/deploymentVQVAE-GitHub/deployment-VQVAE/api_test/results_inference/vqvae_a1_m_best_test_more_data_20260105_191422/test_more_data.pkl
CPU times: user 17 s, sys: 1.69 s, total: 18.7 s
Wall time: 3.02 s

       user                                            indices
0    121094  [255, 225, 163, 251, 52, 216, 40, 53, 67, 130,...
1    301056  [13, 58, 50, 198, 232, 142, 42, 214, 135, 225,...
2    301057  [177, 122, 116, 148, 18, 20, 13, 3, 173, 198, ...
3    301058  [75, 220, 155, 181, 15, 214, 13, 220, 15, 142,...
4    301060  [252, 135, 135, 173, 15, 109, 243, 42, 42, 42,...
5    301061  [232, 135, 173, 224, 225, 211, 211, 110, 251, ...
6    301063  [126, 193, 15, 165, 68, 154, 237, 203, 217, 76...
7    301064  [252, 135, 135, 249, 131, 62, 222, 42, 135, 42...
8    301066  [216, 253, 95, 255, 224, 163, 250, 190, 204, 1...
9    301067  [232, 173, 70, 97, 225, 135, 135, 135, 135, 75...
10   301068  [14, 14, 195, 113, 225, 62, 247, 57, 22, 195, ...
11   301069  [252, 135, 135, 131, 196, 135, 173, 237, 15, 2...
12   301070  [126, 121, 95, 8, 126, 52, 123, 41, 39, 137, 1...
13   301071  [255, 3, 3, 131, 250, 55, 42, 214, 135, 173, 2...
14   301072  [253, 13, 97, 45, 130, 47, 22, 126, 70, 45, 34...
15   301074  [245, 0, 255, 225, 131, 110, 22, 132, 75, 122,...
16   301075  [137, 72, 232, 222, 250, 13, 97, 137, 152, 221...
17   301076  [252, 173, 42, 173, 224, 236, 105, 42, 173, 42...
18   301077  [151, 55, 70, 15, 203, 72, 147, 55, 15, 214, 7...
19   301079  [253, 13, 214, 75, 97, 97, 132, 135, 142, 15, ...
20   301080  [115, 135, 135, 27, 224, 232, 211, 211, 247, 7...
21   301081  [242, 55, 15, 165, 170, 197, 197, 42, 75, 13, ...
22   301082  [14, 14, 195, 113, 225, 62, 110, 110, 37, 95, ...
23   301083  [232, 135, 135, 196, 131, 110, 42, 135, 135, 1...
24   301084  [247, 126, 42, 196, 243, 110, 110, 110, 243, 4...
25   301085  [195, 58, 137, 96, 250, 250, 42, 3, 173, 225, ...
26   301086  [232, 41, 217, 76, 131, 62, 28, 34, 203, 27, 9...
27   301087  [23, 148, 190, 231, 13, 97, 94, 206, 130, 14, ...
28   301088  [154, 121, 109, 109, 224, 96, 34, 49, 121, 15,...
29   301091  [233, 21, 64, 211, 197, 76, 113, 21, 8, 123, 4...
30   301093  [119, 25, 95, 58, 72, 91, 136, 40, 216, 76, 27...
31   301095  [242, 76, 173, 249, 131, 91, 252, 178, 217, 13...
32   301096  [186, 149, 97, 249, 249, 50, 251, 247, 144, 15...
33   301097                        [22, 40, 200, 76, 236, 123]
34   301098  [195, 76, 131, 131, 236, 252, 131, 197, 13, 97...
35   301100  [194, 13, 58, 225, 185, 151, 151, 197, 75, 58,...
36   301101  [200, 233, 82, 57, 22, 40, 40, 46, 137, 82, 12...
37   301102  [185, 178, 42, 3, 173, 131, 243, 79, 42, 13, 1...
38   301103  [157, 52, 105, 3, 76, 131, 142, 110, 154, 237,...
39   301104  [40, 163, 151, 42, 173, 213, 232, 135, 250, 21...
40   301106  [204, 190, 42, 173, 173, 225, 252, 135, 135, 1...
41   301107  [128, 128, 121, 95, 102, 68, 154, 34, 247, 251...
42   521052  [23, 23, 23, 185, 204, 250, 75, 13, 255, 249, ...
43   521075                                              [247]
44   821046  [185, 42, 3, 173, 224, 232, 55, 42, 42, 135, 1...
45   841063  [216, 28, 27, 172, 100, 230, 242, 53, 105, 58,...
46  2011151  [148, 13, 75, 122, 154, 68, 142, 237, 214, 42,...
47  2011153  [137, 100, 250, 194, 75, 75, 97, 100, 225, 178...

In [11]:
%%time

inference.device = "cuda"
inference.forward(data_path = data_path,
                  results_folder_path = results_folder_path,
)

Data successfully loaded
User index with duplicates: 301059
Duplicated dates:
        user  date_time      service  sleep_start  location_distance  \
894  301059 2024-12-30  DC_alicante          NaN                NaN
893  301059 2024-12-30  DC_alicante          NaN                NaN
840  301059 2024-12-31  DC_alicante          NaN                NaN
839  301059 2024-12-31  DC_alicante          NaN                NaN

     location_time_home  sleep_duration  activity_walking  app_usage_total  \
894                 NaN             NaN            6593.0              NaN
893                 NaN             NaN               NaN              NaN
840                 NaN             NaN               NaN              NaN
839                 NaN             NaN               NaN              NaN

     location_clusters_count  steps_steps_total  weekend  practiced_sport
894                      NaN             7939.0        0                1
893                      NaN                NaN        0                0
840                      NaN                NaN        0                0
839                      NaN                NaN        0                0
User index with duplicates: 301092
Duplicated dates:
        user  date_time      service  sleep_start  location_distance  \
910  301092 2024-12-30  DC_alicante          NaN                NaN
909  301092 2024-12-30  DC_alicante     -11824.0                NaN
856  301092 2024-12-31  DC_alicante          NaN                NaN
855  301092 2024-12-31  DC_alicante          NaN                NaN

     location_time_home  sleep_duration  activity_walking  app_usage_total  \
910                 NaN             NaN               NaN              NaN
909                 NaN         40200.0               NaN              NaN
856                 NaN             NaN               NaN              NaN
855                 NaN             NaN               NaN              NaN

     location_clusters_count  steps_steps_total  weekend  practiced_sport
910                      NaN             8191.0        0                0
909                      NaN                NaN        0                0
856                      NaN                NaN        0                0
855                      NaN                NaN        0                0

Out of 50, 48 were kept, and 2 were discarded due to duplicated dates.

[841063, 821046, 121094, 521052, 521075, 301056, 301057, 301058, 301101, 301060, 301061, 301063, 301064, 301066, 301068, 301069, 301075, 301079, 301077, 301076, 301067, 301074, 301072, 301091, 301097, 301093, 301088, 301086, 301083, 301082, 301081, 301080, 301084, 301071, 301070, 301098, 2011153, 301087, 301102, 301103, 301104, 301106, 301107, 301095, 301096, 2011151, 301100, 301085]
Patient ID: 841063, sample shape: (52, 13)
Patient ID: 821046, sample shape: (46, 13)
Patient ID: 121094, sample shape: (46, 13)
Patient ID: 521052, sample shape: (29, 13)
Patient ID: 521075, sample shape: (1, 13)
Patient ID: 301056, sample shape: (137, 13)
Patient ID: 301057, sample shape: (46, 13)
Patient ID: 301058, sample shape: (224, 13)
Patient ID: 301101, sample shape: (495, 13)
Patient ID: 301060, sample shape: (24, 13)
Patient ID: 301061, sample shape: (99, 13)
Patient ID: 301063, sample shape: (219, 13)
Patient ID: 301064, sample shape: (204, 13)
Patient ID: 301066, sample shape: (156, 13)
Patient ID: 301068, sample shape: (219, 13)
Patient ID: 301069, sample shape: (220, 13)
Patient ID: 301075, sample shape: (437, 13)
Patient ID: 301079, sample shape: (123, 13)
Patient ID: 301077, sample shape: (213, 13)
Patient ID: 301076, sample shape: (113, 13)
Patient ID: 301067, sample shape: (146, 13)
Patient ID: 301074, sample shape: (191, 13)
Patient ID: 301072, sample shape: (118, 13)
Patient ID: 301091, sample shape: (151, 13)
Patient ID: 301097, sample shape: (6, 13)
Patient ID: 301093, sample shape: (159, 13)
Patient ID: 301088, sample shape: (206, 13)
Patient ID: 301086, sample shape: (147, 13)
Patient ID: 301083, sample shape: (206, 13)
Patient ID: 301082, sample shape: (41, 13)
Patient ID: 301081, sample shape: (476, 13)
Patient ID: 301080, sample shape: (85, 13)
Patient ID: 301084, sample shape: (184, 13)
Patient ID: 301071, sample shape: (205, 13)
Patient ID: 301070, sample shape: (203, 13)
Patient ID: 301098, sample shape: (144, 13)
Patient ID: 2011153, sample shape: (50, 13)
Patient ID: 301087, sample shape: (217, 13)
Patient ID: 301102, sample shape: (200, 13)
Patient ID: 301103, sample shape: (100, 13)
Patient ID: 301104, sample shape: (124, 13)
Patient ID: 301106, sample shape: (83, 13)
Patient ID: 301107, sample shape: (24, 13)
Patient ID: 301095, sample shape: (198, 13)
Patient ID: 301096, sample shape: (26, 13)
Patient ID: 2011151, sample shape: (73, 13)
Patient ID: 301100, sample shape: (358, 13)
Patient ID: 301085, sample shape: (195, 13)
Forwarded Batch
Dataset saved to: /export/usuarios01/icmora/deploymentVQVAE-GitHub/deployment-VQVAE/api_test/results_inference/vqvae_a1_m_best_test_more_data_20260105_215522/test_more_data.pkl
CPU times: user 4.41 s, sys: 9.3 ms, total: 4.42 s
Wall time: 4.43 s

       user                                            indices
0    121094  [255, 225, 163, 251, 52, 216, 40, 53, 67, 130,...
1    301056  [13, 97, 50, 198, 232, 142, 238, 214, 173, 225...
2    301057  [177, 122, 116, 148, 18, 20, 13, 3, 210, 198, ...
3    301058  [75, 220, 155, 181, 155, 214, 220, 220, 15, 14...
4    301060  [252, 135, 135, 173, 238, 214, 243, 42, 42, 42...
5    301061  [232, 135, 173, 224, 225, 211, 135, 110, 12, 1...
6    301063  [126, 193, 15, 165, 68, 154, 237, 203, 217, 76...
7    301064  [252, 197, 135, 249, 131, 62, 222, 42, 135, 42...
8    301066  [216, 253, 95, 97, 225, 163, 250, 190, 204, 13...
9    301067  [232, 173, 238, 97, 225, 135, 135, 135, 135, 7...
10   301068  [14, 14, 195, 113, 225, 62, 247, 57, 22, 195, ...
11   301069  [252, 135, 135, 131, 196, 135, 135, 70, 238, 2...
12   301070  [126, 121, 95, 8, 126, 52, 123, 41, 39, 137, 1...
13   301071  [255, 3, 3, 131, 250, 55, 238, 214, 135, 173, ...
14   301072  [253, 13, 97, 45, 130, 47, 22, 126, 70, 210, 3...
15   301074  [245, 0, 255, 225, 131, 110, 22, 132, 75, 122,...
16   301075  [137, 72, 232, 222, 250, 13, 97, 137, 152, 221...
17   301076  [252, 173, 42, 210, 225, 236, 105, 42, 173, 42...
18   301077  [151, 55, 70, 15, 210, 72, 147, 55, 238, 214, ...
19   301079  [253, 13, 214, 97, 97, 97, 156, 135, 142, 238,...
20   301080  [115, 197, 197, 27, 224, 232, 135, 135, 247, 7...
21   301081  [242, 55, 15, 165, 170, 79, 197, 42, 75, 13, 1...
22   301082  [14, 164, 195, 113, 225, 62, 110, 110, 12, 95,...
23   301083  [232, 135, 135, 196, 131, 110, 238, 135, 135, ...
24   301084  [247, 126, 238, 196, 243, 110, 110, 110, 243, ...
25   301085  [195, 58, 137, 96, 250, 250, 42, 3, 173, 225, ...
26   301086  [232, 41, 217, 76, 131, 62, 28, 34, 203, 27, 9...
27   301087  [23, 148, 190, 231, 13, 97, 120, 206, 130, 14,...
28   301088  [154, 121, 109, 170, 224, 96, 34, 49, 121, 15,...
29   301091  [233, 21, 64, 211, 197, 76, 113, 91, 8, 123, 4...
30   301093  [119, 164, 95, 58, 72, 91, 136, 40, 216, 76, 2...
31   301095  [242, 76, 173, 249, 131, 91, 252, 178, 217, 13...
32   301096  [186, 149, 97, 249, 225, 50, 251, 247, 144, 95...
33   301097                        [22, 40, 200, 76, 236, 123]
34   301098  [195, 76, 131, 131, 236, 252, 131, 197, 13, 97...
35   301100  [194, 13, 58, 225, 185, 151, 151, 197, 75, 58,...
36   301101  [200, 233, 82, 57, 22, 22, 40, 46, 137, 236, 1...
37   301102  [185, 178, 42, 3, 210, 131, 213, 79, 42, 42, 2...
38   301103  [157, 52, 105, 3, 76, 131, 142, 110, 154, 237,...
39   301104  [40, 163, 151, 42, 210, 213, 232, 135, 250, 21...
40   301106  [204, 190, 42, 173, 173, 225, 225, 135, 135, 1...
41   301107  [128, 128, 121, 95, 102, 68, 154, 34, 247, 251...
42   521052  [23, 23, 23, 185, 204, 250, 75, 13, 97, 225, 1...
43   521075                                              [247]
44   821046  [185, 42, 3, 210, 224, 232, 55, 42, 42, 135, 1...
45   841063  [216, 239, 27, 172, 100, 230, 242, 53, 105, 58...
46  2011151  [148, 13, 75, 122, 154, 68, 142, 238, 214, 42,...
47  2011153  [137, 100, 250, 194, 75, 75, 97, 100, 225, 178...